services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      # Passing the db name automatically create it for us
      - NZYME_POSTGRES_DB=${NZYME_POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nzyme_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  # nzyme_tap:
  #   image: nzyme-tap:latest
  #   environment:
  #     - TAP_SECRET_KEY=${TAP_SECRET_KEY}
  #   volumes:
  #     - ./nzyme-tap/start.sh:/tmp/start.sh
  #   cap_add:
  #     - NET_ADMIN
  #   network_mode: host

  nzyme_node:
    image: nzyme-node:latest
    restart: on-failure
    ports:
      - "${NZYME_PORT}:${NZYME_PORT}"
    environment:
      - NZYME_POSTGRES_DB=${NZYME_POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - NZYME_PORT=${NZYME_PORT}
      - NZYME_URI=${NZYME_URI}
      - NZYME_NODE_NAME=${NZYME_NODE_NAME}
    networks:
      - nzyme_network
    volumes:
      - ./nzyme_node/nzyme.conf.template:/etc/nzyme/nzyme.conf.template
      - ./nzyme_node/start.sh:/tmp/start.sh
      - ./nzyme_node/node_id:/usr/share/nzyme/node_id
      - nzyme_node_keys:/usr/share/nzyme/crypto

volumes:
  postgres_data:
  nzyme_node_keys:

networks:
  nzyme_network:
    driver: bridge