name: Nzyme Docker images

on:
  push:
    branches:
      - 'main'

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v4
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          # TODO: Not so much a secret but trying getting vars to use but couldn't... so this will do
          IMAGE_REGISTRY_PREFIX: ${{ secrets.IMAGE_REGISTRY_PREFIX }}
        with:
          push: true
          targets: all_nzyme_nodes, all_nzyme_taps
          files: |
            ./docker-bake.hcl
